WITH RECURSIVE TEMP AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM TEMP
    WHERE HOUR>23
)

SELECT HOUR(ANIMAL_OUTS.DATETIME), COUNT(HOUR(ANIMAL_OUTS.DATETIME)) FROM ANIMAL_OUTS
    TEMP LEFT JOIN ANIMAL_OUTS
    ON TEMP.HOUR = HOUR(ANIMAL_OUTS.DATETIME)
    GROUP BY HOUR(DATETIME)
    ORDER BY 1;